gpu_tonemapper: fix build with VNDK
The module is using glTexImage3D which is a GLESv3 API.

hardware/qcom/display/sde/gpu_tonemapper/glengine.cpp:150: error: undefined reference to 'glTexImage3D'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)

Signed-off-by: David Viteri <davidteri91@gmail.com>